(deftheme drn-dark
  "Created 2025-10-20.")

(custom-theme-set-faces
 'drn-dark
 '(cursor ((t (:background "#5DD8FF"))))
 '(fixed-pitch ((t (:family "JetBrains Mono" :foundry "nil" :width normal :height 140 :weight regular :slant normal))))
 '(variable-pitch ((t (:family "Helvetica Neue" :foundry "nil" :width normal :height 160 :weight regular :slant normal))))
 '(escape-glyph ((t (:foreground "#8abeb7"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#5DD8FF"))))
 '(highlight ((t (:background "gray36" :foreground "gray95"))))
 '(region ((t (:extend t :background "wheat4"))))
 '(shadow ((t (:foreground "#5c5e5e"))))
 '(secondary-selection ((t (:extend t :background "gray33"))))
 '(trailing-whitespace ((t (:background "#FC6A5D"))))
 '(font-lock-bracket-face ((t (:inherit default))))
 '(font-lock-builtin-face ((t (:foreground "gray96"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:background "gray30" :foreground "gray64"))))
 '(font-lock-constant-face ((t (:foreground "plum3"))))
 '(font-lock-delimiter-face ((t (:inherit default))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#808b96"))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-constant-face))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t nil)))
 '(font-lock-function-name-face ((t (:foreground "gray96"))))
 '(font-lock-keyword-face ((t (:foreground "gray96" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t (:foreground "chartreuse3"))))
 '(font-lock-misc-punctuation-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-property-name-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-property-use-face ((t (:inherit font-lock-property-name-face))))
 '(font-lock-punctuation-face ((t (:inherit default))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:background "#305768" :foreground "LightCyan1"))))
 '(font-lock-type-face ((t (:foreground "LightCyan1"))))
 '(font-lock-variable-name-face ((t (:foreground "LightBlue1"))))
 '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#5DD8FF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:foreground "#3f4040" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#252629" :background "#ffffff"))))
 '(mode-line ((t (:background "gray23" :foreground "#fafafa"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "DarkOliveGreen4"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "gray14" :foreground "#fafafa"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#0d0d0d" :background "#FC6A5D"))))
 '(lazy-highlight ((t (:weight bold :foreground "#ffffff" :background "#4197b2"))))
 '(match ((t (:weight bold :foreground "#67B7A4" :background "#0d0d0d"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(cperl-hash-face ((t (:inherit font-lock-variable-name-face))))
 '(cperl-nonoverridable-face ((t (:inherit font-lock-variable-name-face))))
 '(cperl-array-face ((t (:inherit font-lock-variable-name-face))))
 '(package-name ((t (:inherit (link)))))
 '(tab-bar ((t (:inherit default))))
 '(tab-line ((t (:inherit default :height 1))))
 '(tab-bar-tab ((t (:inherit tab-bar :box (:line-width (1 . 1) :style released-button)))))
 '(tab-bar-tab-inactive ((t (:inherit tab-bar-tab))))
 '(tab-bar-tab-ungrouped ((t (:inherit shadow))))
 '(tab-bar-tab-group-current ((t (:weight bold :box nil :inherit (tab-bar-tab)))))
 '(tab-bar-tab-group-inactive ((t (:inherit shadow))))
 '(diredfl-file-name ((t (:inherit default))))
 '(diredfl-dir-name ((t (:foreground "LightBlue3"))))
 '(elisp-shorthand-font-lock-face ((t (:inherit font-lock-keyword-face))))
 '(diredfl-file-suffix ((t (:foreground "LightBlue2"))))
 '(diredfl-date-time ((t (:inherit default))))
 '(diredfl-number ((t (:inherit font-lock-number-face))))
 '(diredfl-exec-priv ((t (:inherit default))))
 '(diredfl-dir-priv ((t (:inherit default))))
 '(diredfl-rare-priv ((t (:inherit default))))
 '(diredfl-link-priv ((t (:inherit default))))
 '(diredfl-write-priv ((t (:inherit default))))
 '(diredfl-no-priv ((t (:inherit default))))
 '(diredfl-read-priv ((t (:inherit default))))
 '(diredfl-other-priv ((t (:inherit default))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "gray20" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 140 :width normal :foundry "nil" :family "JetBrains Mono"))))
 '(envrc-mode-line-on-face ((t (:inherit (success)))))
 '(doom-modeline-lsp-success ((t (:inherit (doom-modeline-info)))))
 '(doom-modeline-info ((t (:inherit (doom-modeline success)))))
 '(success ((t (:foreground "PaleGreen3" :weight bold))))
 '(diredfl-deletion ((t (:background "red4" :foreground "LightYellow1"))))
 '(diredfl-deletion-file-name ((t (:foreground "red3")))))

(provide-theme 'drn-dark)
