(deftheme drn-dark
  "Created 2025-10-20.")

(custom-theme-set-faces
 'drn-dark
 '(cursor ((t (:background "#5DD8FF"))))
 '(fixed-pitch ((t (:family "JetBrains Mono" :foundry "nil" :width normal :height 140 :weight regular :slant normal))))
 '(variable-pitch ((t (:family "Helvetica Neue" :foundry "nil" :width normal :height 160 :weight regular :slant normal))))
 '(escape-glyph ((t (:foreground "#8abeb7"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#5DD8FF"))))
 '(highlight ((t (:background "gray25"))))
 '(region ((t (:extend t :background "grey30"))))
 '(shadow ((t (:foreground "#5c5e5e"))))
 '(secondary-selection ((t (:extend t :background "gray33"))))
 '(trailing-whitespace ((t (:background "#FC6A5D"))))
 '(font-lock-bracket-face ((t (:inherit default))))
 '(font-lock-builtin-face ((t (:foreground "gray96"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:background "gray30" :foreground "gray64"))))
 '(font-lock-constant-face ((t (:foreground "plum3"))))
 '(font-lock-delimiter-face ((t (:inherit default))))
 '(font-lock-doc-face ((t (:foreground "LightGoldenrod1" :background "grey25"))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-keyword-face))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit default))))
 '(font-lock-function-name-face ((t (:foreground "DarkSeaGreen1" :weight semibold :background "gray25"))))
 '(font-lock-keyword-face ((t (:foreground "white" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t (:foreground "SkyBlue1"))))
 '(font-lock-misc-punctuation-face ((t (:inherit font-lock-punctuation-face))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-property-name-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-property-use-face ((t (:inherit font-lock-property-name-face))))
 '(font-lock-punctuation-face ((t (:inherit default))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:background "#305768" :foreground "LightCyan1"))))
 '(font-lock-type-face ((t (:foreground "LightCyan1"))))
 '(font-lock-variable-name-face ((t (:foreground "LightBlue1"))))
 '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:foreground "#3f4040" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#252629" :background "#ffffff"))))
 '(mode-line ((t (:inherit default))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "chartreuse3"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "gray20" :foreground "gray50"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#0d0d0d" :background "#FC6A5D"))))
 '(lazy-highlight ((t (:weight bold :foreground "#ffffff" :background "#4197b2"))))
 '(match ((t (:weight bold :foreground "#67B7A4" :background "#0d0d0d"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(cperl-hash-face ((t (:inherit font-lock-variable-name-face))))
 '(cperl-nonoverridable-face ((t (:inherit font-lock-variable-name-face))))
 '(cperl-array-face ((t (:inherit font-lock-variable-name-face))))
 '(package-name ((t (:inherit (link)))))
 '(tab-bar ((t (:inherit default))))
 '(tab-bar-tab ((t (:inherit tab-bar :box (:line-width (3 . 3) :style flat-button)))))
 '(tab-bar-tab-inactive ((t (:background "grey30" :foreground "grey70" :box (:line-width (3 . 3) :style flat-button)))))
 '(tab-bar-tab-ungrouped ((t (:inherit shadow))))
 '(tab-bar-tab-group-current ((t (:weight bold :box nil :inherit (tab-bar-tab)))))
 '(tab-bar-tab-group-inactive ((t (:background "grey30"))))
 '(diredfl-file-name ((t (:foreground "LightBlue3"))))
 '(diredfl-dir-name ((t (:foreground "LightBlue3"))))
 '(elisp-shorthand-font-lock-face ((t (:inherit font-lock-keyword-face))))
 '(diredfl-file-suffix ((t (:inherit font-lock-constant-face))))
 '(diredfl-date-time ((t (:inherit font-lock-number-face))))
 '(diredfl-number ((t (:inherit font-lock-number-face))))
 '(diredfl-exec-priv ((t (:inherit font-lock-string-face))))
 '(diredfl-dir-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-rare-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-link-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-write-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-no-priv ((t (:background "grey25"))))
 '(diredfl-read-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-other-priv ((t (:inherit diredfl-no-priv))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "gray20" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 140 :width normal :foundry "nil" :family "JetBrains Mono"))))
 '(envrc-mode-line-on-face ((t (:inherit (success)))))
 '(doom-modeline-lsp-success ((t (:inherit (doom-modeline-info)))))
 '(doom-modeline-info ((t (:inherit (doom-modeline success)))))
 '(success ((t (:foreground "PaleGreen3" :weight bold))))
 '(diredfl-deletion ((t (:background "red4" :foreground "LightYellow1"))))
 '(diredfl-deletion-file-name ((t (:foreground "red3"))))
 '(ansi-color-green ((t (:background "chartreuse3" :foreground "chartreuse3"))))
 '(ansi-color-red ((t (:background "firebrick3" :foreground "firebrick3"))))
 '(ansi-color-blue ((t (:background "DodgerBlue3" :foreground "DodgerBlue3"))))
 '(ansi-color-cyan ((t (:background "LightBlue2" :foreground "LightBlue2"))))
 '(ansi-color-black ((t (:background "black" :foreground "black"))))
 '(ansi-color-white ((t (:background "gray90" :foreground "grey90"))))
 '(ansi-color-yellow ((t (:background "systemYellowColor" :foreground "systemYellowColor"))))
 '(ansi-color-magenta ((t (:background "orchid4" :foreground "orchid4"))))
 '(ansi-color-bright-red ((t (:background "firebrick2" :foreground "firebrick2"))))
 '(ansi-color-bright-blue ((t (:background "DodgerBlue3" :foreground "DodgerBlue3"))))
 '(ansi-color-bright-cyan ((t (:background "LightBlue2" :foreground "LightBlue2"))))
 '(ansi-color-bright-black ((t (:background "gray50" :foreground "gray50"))))
 '(ansi-color-bright-green ((t (:background "chartreuse2" :foreground "chartreuse2"))))
 '(ansi-color-bright-white ((t (:background "gray99" :foreground "gray99"))))
 '(ansi-color-bright-yellow ((t (:background "gold1" :foreground "gold1"))))
 '(ansi-color-bright-magenta ((t (:background "orchid3" :foreground "orchid3"))))
 '(web-mode-comment-face ((t (:inherit (font-lock-comment-face)))))
 '(web-mode-html-attr-name-face ((t (:foreground "gray75"))))
 '(web-mode-html-tag-face ((t (:inherit font-lock-function-name-face))))
 '(web-mode-html-attr-equal-face ((t (:inherit (web-mode-html-attr-name-face)))))
 '(web-mode-html-attr-value-face ((t (:inherit default))))
 '(web-mode-function-call-face ((t (:inherit default))))
 '(web-mode-function-name-face ((t (:inherit default))))
 '(web-mode-filter-face ((t (:inherit default))))
 '(web-mode-html-tag-custom-face ((t (:inherit (web-mode-html-tag-face)))))
 '(web-mode-html-tag-bracket-face ((t (:inherit font-lock-keyword-face :weight semi-bold))))
 '(web-mode-part-face ((t (:background "gray99"))))
 '(web-mode-block-face ((t (:background "gray99"))))
 )

(provide-theme 'drn-dark)
