(deftheme drn-light
  "Created 2025-10-20.")

(custom-theme-set-faces
 'drn-light
 '(cursor ((t (:background "#5DD8FF"))))
 '(fixed-pitch ((t (:family "JetBrains Mono" :foundry "nil" :width normal :height 140 :weight regular :slant normal))))
 '(variable-pitch ((t (:family "Helvetica Neue" :foundry "nil" :width normal :height 160 :weight regular :slant normal))))
 '(escape-glyph ((t (:foreground "#8abeb7"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "chartreuse4"))))
 '(highlight ((t (:background "gray95"))))
 '(region ((t (:extend t :background "gray98"))))
 '(shadow ((t (:foreground "#5c5e5e"))))
 '(secondary-selection ((t (:extend t :background "gray90"))))
 '(trailing-whitespace ((t (:background "#FC6A5D"))))
 '(font-lock-bracket-face ((t (:inherit font-lock-keyword-face))))
 '(font-lock-builtin-face ((t (:foreground "gray19"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "gray60" :background "gray99"))))
 '(font-lock-constant-face ((t (:foreground "plum4"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:background "ivory" :foreground "DarkGoldenrod4"))))
 '(font-lock-doc-markup-face ((t (:inherit link))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit default))))
 '(font-lock-function-name-face ((t (:foreground "chartreuse4" :background "honeydew1"))))
 '(font-lock-keyword-face ((t (:foreground "gray19" :weight semi-bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t (:foreground "DeepSkyBlue3"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:background "azure1" :foreground "SkyBlue4"))))
 '(font-lock-type-face ((t (:foreground "#292A30"))))
 '(font-lock-variable-name-face ((t (:foreground "#41A1C0"))))
 '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight semi-bold))))
 '(link-visited ((t (:foreground "magenta4" :inherit (link)))))
 '(fringe ((t (:foreground "#3f4040" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#252629" :background "#ffffff"))))
 '(mode-line ((t (:background "gray94" :foreground "#191a1c"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "charteuse4"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "gray97" :foreground "#303030"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#0d0d0d" :background "#FC6A5D"))))
 '(lazy-highlight ((t (:weight bold :foreground "#ffffff" :background "#4197b2"))))
 '(match ((t (:weight bold :foreground "#67B7A4" :background "#0d0d0d"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(cperl-hash-face ((t (:inherit font-lock-variable-name-face))))
 '(cperl-nonoverridable-face ((t (:inherit default))))
 '(cperl-array-face ((t (:inherit font-lock-variable-name-face))))
 '(package-name ((t (:inherit (link)))))
 '(tab-bar ((t (:inherit default))))
 '(tab-line ((t (:background "grey85" :foreground "black" :height 1))))
 '(tab-bar-tab ((t (:inherit tab-bar :box (:line-width (3 . 3) :style flat-button)))))
 '(tab-bar-tab-inactive ((t (:background "grey75" :foreground "white" :box (:line-width (3 . 3) :style flat-button)))))
 '(tab-bar-tab-ungrouped ((t (:inherit tab-bar-tab))))
 '(tab-bar-tab-group-current ((t (:inherit tab-bar-tab-inactive :box nil :weight bold))))
 '(tab-bar-tab-group-inactive ((t (:inherit tab-bar-tab-inactive))))
 '(diredfl-file-name ((t (:foreground "DodgerBlue4"))))
 '(diredfl-dir-name ((t (:foreground "DeepSkyBlue4"))))
 '(elisp-shorthand-font-lock-face ((t (:foreground "cyan" :inherit (font-lock-keyword-face)))))
 '(diredfl-deletion-file-name ((t (:foreground "Red"))))
 '(diredfl-deletion ((t (:background "Red" :foreground "Yellow"))))
 '(diredfl-other-priv ((t (:background "LightYellow1" :foreground "DarkOrange4"))))
 '(diredfl-read-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-no-priv ((t (:background "gray99"))))
 '(diredfl-write-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-rare-priv ((t (:inherit diredfl-no-priv))))
 '(diredfl-dir-priv ((t (:inherit dired-no-priv))))
 '(diredfl-exec-priv ((t (:background "LightCyan1" :foreground "DodgerBlue4"))))
 '(diredfl-number ((t (:inherit font-lock-number-face))))
 '(diredfl-date-time ((t (:inherit font-lock-number-face))))
 '(diredfl-link-priv ((((background dark)) (:foreground "#00007373FFFF")) (t (:foreground "DarkOrange"))))
 '(diredfl-file-suffix ((((background dark)) (:foreground "#7474FFFF7474")) (t (:foreground "DarkMagenta"))))
 '(ansi-color-green ((t (:background "chartreuse4" :foreground "chartreuse4"))))
 '(ansi-color-red ((t (:background "firebrick4" :foreground "firebrick4"))))
 '(ansi-color-blue ((t (:background "DodgerBlue4" :foreground "DodgerBlue4"))))
 '(ansi-color-cyan ((t (:background "LightBlue3" :foreground "LightBlue3"))))
 '(ansi-color-black ((t (:background "gray17" :foreground "gray17"))))
 '(ansi-color-white ((t (:background "gray90" :foreground "grey90"))))
 '(ansi-color-yellow ((t (:background "systemYellowColor" :foreground "systemYellowColor"))))
 '(ansi-color-magenta ((t (:background "orchid4" :foreground "orchid4"))))
 '(ansi-color-bright-red ((t (:background "firebrick2" :foreground "firebrick2"))))
 '(ansi-color-bright-blue ((t (:background "DodgerBlue3" :foreground "DodgerBlue3"))))
 '(ansi-color-bright-cyan ((t (:background "LightBlue2" :foreground "LightBlue2"))))
 '(ansi-color-bright-black ((t (:background "gray30" :foreground "gray30"))))
 '(ansi-color-bright-green ((t (:background "chartreuse2" :foreground "chartreuse2"))))
 '(ansi-color-bright-white ((t (:background "gray99" :foreground "gray99"))))
 '(ansi-color-bright-yellow ((t (:background "gold1" :foreground "gold1"))))
 '(ansi-color-bright-magenta ((t (:background "orchid3" :foreground "orchid3"))))
 '(web-mode-comment-face ((t (:inherit (font-lock-comment-face)))))
 '(web-mode-html-attr-name-face ((t (:foreground "gray50"))))
 '(web-mode-html-tag-face ((t (:inherit font-lock-keyword-face))))
 '(web-mode-html-attr-equal-face ((t (:inherit (web-mode-html-attr-name-face)))))
 '(web-mode-html-attr-value-face ((t (:inherit default))))
 '(web-mode-function-call-face ((t (:inherit default))))
 '(web-mode-function-name-face ((t (:inherit default))))
 '(web-mode-filter-face ((t (:inherit default))))
 '(web-mode-html-tag-custom-face ((t (:inherit (web-mode-html-tag-face)))))
 '(web-mode-html-tag-bracket-face ((t (:inherit font-lock-bracket-face :weight semi-bold))))
 '(web-mode-part-face ((t (:background "gray99"))))
 '(web-mode-block-face ((t (:background "gray99"))))
 '(font-lock-regexp-face ((t (:inherit (font-lock-string-face)))))
 '(lsp-face-semhl-regexp ((t (:slant italic :inherit (font-lock-string-face)))))
 '(cperl-method-call ((t (:inherit default))))
 '(default ((t (:family "JetBrains Mono" :foundry "nil" :width normal :height 140 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#292A30" :background "#FFFFFF" :stipple nil :inherit nil)))))

(provide-theme 'drn-light)
